// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzNM1VBx4iEhb9Lq27j7qok8-msfIc4QY',
    appId: '1:205543271273:web:7cc4036946bd7a16732bf8',
    messagingSenderId: '205543271273',
    projectId: 'chatapp-57f95',
    authDomain: 'chatapp-57f95.firebaseapp.com',
    databaseURL: 'https://chatapp-57f95-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-57f95.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqiuODucUiRyHQdh5_pPxOKQSamGQu7Ys',
    appId: '1:205543271273:android:8abe0db19747d896732bf8',
    messagingSenderId: '205543271273',
    projectId: 'chatapp-57f95',
    databaseURL: 'https://chatapp-57f95-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-57f95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDolZXS_M92MSEyUkO2JC6rn9kr2Adjj7c',
    appId: '1:205543271273:ios:f7d3141d19acff71732bf8',
    messagingSenderId: '205543271273',
    projectId: 'chatapp-57f95',
    databaseURL: 'https://chatapp-57f95-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-57f95.appspot.com',
    androidClientId: '205543271273-3g6aqq38dpk05em77smml24j34u7ftkj.apps.googleusercontent.com',
    iosClientId: '205543271273-n8np15sinlgd2jmk6bl62vrmuldgiotq.apps.googleusercontent.com',
    iosBundleId: 'com.uttamlaila.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDolZXS_M92MSEyUkO2JC6rn9kr2Adjj7c',
    appId: '1:205543271273:ios:f7d3141d19acff71732bf8',
    messagingSenderId: '205543271273',
    projectId: 'chatapp-57f95',
    databaseURL: 'https://chatapp-57f95-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-57f95.appspot.com',
    androidClientId: '205543271273-3g6aqq38dpk05em77smml24j34u7ftkj.apps.googleusercontent.com',
    iosClientId: '205543271273-n8np15sinlgd2jmk6bl62vrmuldgiotq.apps.googleusercontent.com',
    iosBundleId: 'com.uttamlaila.chatApp',
  );
}
